# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-gallery-doubletap-zoomout

# >> macros
BuildArch: noarch
# << macros

Summary:    Gallery doubletap reset scale
Version:    0.0.1
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager

%description
Patch for resetting image scale in gallery by double click.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-gallery-doubletap-zoomout
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-gallery-doubletap-zoomout
# << install pre

# >> install post
# << install post

%pre
# >> pre
if [ -f /usr/sbin/patchmanager ]; then
/usr/sbin/patchmanager -u sailfishos-gallery-doubletap-zoomout || true
fi
# << pre

%preun
# >> preun
if [ -f /usr/sbin/patchmanager ]; then
/usr/sbin/patchmanager -u sailfishos-gallery-doubletap-zoomout || true
fi
# << preun

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-gallery-doubletap-zoomout
# >> files
# << files
